<?php

namespace Mchekin\RpgRuleset\Tests\Unit;


use DomainException;
use Mchekin\RpgRuleset\Attribute;
use Mchekin\RpgRuleset\AttributeBuilder;
use Mchekin\RpgRuleset\CharacterBuilder;
use Mockery;
use PHPUnit\Framework\TestCase;

class CharacterBuilderTest extends TestCase
{
    /**
     * @var Mockery\MockInterface|AttributeBuilder
     */
    private $attributeBuilder;

    /**
     * @var Mockery\MockInterface|Attribute
     */
    private $attribute;

    /**
     * @var CharacterBuilder
     */
    private $characterBuilder;

    public function setUp()
    {
        parent::setUp();

        $this->attribute= Mockery::mock(Attribute::class);

        $this->attributeBuilder = Mockery::mock(AttributeBuilder::class);

        $this->characterBuilder = new CharacterBuilder($this->attributeBuilder);
    }

    public function tearDown()
    {
        Mockery::close();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @dataProvider characterDataProvider
     * @param string $name
     * @param string $gender
     * @param string $race
     * @param string $class
     */
    public function generatesCharacter(string $name, string $gender, string $race, string $class)
    {
        // Arrange
        $this->attributeBuilder->shouldReceive('build')->times(6)->andReturn(rand(3, 18));

        // Act
        $character = $this->characterBuilder
            ->setName($name)
            ->setGender($gender)
            ->setRace($race)
            ->setClass($class)
            ->build();

        // Assert
        $this->assertLessThanOrEqual(18, $character->getStrength());
        $this->assertLessThanOrEqual(18, $character->getAgility());
        $this->assertLessThanOrEqual(18, $character->getConstitution());
        $this->assertLessThanOrEqual(18, $character->getIntelligence());
        $this->assertLessThanOrEqual(18, $character->getWisdom());
        $this->assertLessThanOrEqual(18, $character->getCharisma());

        $this->assertGreaterThanOrEqual(3, $character->getStrength());
        $this->assertGreaterThanOrEqual(3, $character->getAgility());
        $this->assertGreaterThanOrEqual(3, $character->getConstitution());
        $this->assertGreaterThanOrEqual(3, $character->getIntelligence());
        $this->assertGreaterThanOrEqual(3, $character->getWisdom());
        $this->assertGreaterThanOrEqual(3, $character->getCharisma());

        $this->assertSame($name, $character->getName());
        $this->assertSame($gender, $character->getGender());
        $this->assertSame($race, $character->getRace());
        $this->assertSame($class, $character->getClass());
    }

    /**
     * @return array
     */
    public function characterDataProvider()
    {
        return [
            ['Jorik', 'Male', 'Human', 'Paladin'],
            ['Julia', 'Female', 'Elf', 'Thief'],
            ['Gork', 'Male', 'Half-orc', 'Warrior'],
            ['Rosksana', 'Shemale', 'Dwarf', 'Priest'],
        ];
    }

    /**
     * @test
     * @expectedException DomainException
     * @expectedExceptionMessage Unsupported character gender Stone.
     */
    public function throwsExceptionOnUnsupportedCharacterGender()
    {
        // Arrange

        // Act
        $this->characterBuilder->setGender('Stone');

        // Assert
    }

    /**
     * @test
     * @expectedException DomainException
     * @expectedExceptionMessage Unsupported character race Munchkin.
     */
    public function throwsExceptionOnUnsupportedCharacterRace()
    {
        // Arrange

        // Act
        $this->characterBuilder->setRace('Munchkin');

        // Assert
    }

    /**
     * @test
     * @expectedException DomainException
     * @expectedExceptionMessage Unsupported character class Space Monkey.
     */
    public function throwsExceptionOnUnsupportedCharacterClass()
    {
        // Arrange

        // Act
        $this->characterBuilder->setClass('Space Monkey');

        // Assert
    }
}